name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    - uses: tlambert03/setup-qt-libs@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Create venv
      run: |
        python310 -m venv env
        source env/bin/activate
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb x11-utils libxkbcommon-x11-0
        pip install -r requirements.txt
        pip install coverage
           
    
    - name: Run tests
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        sudo xvfb-run --auto-servernum `which coverage` run -m pytest
